language: csharp


matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131


script:
  # Run a new console app
  - dotnet restore
  - dotnet test test/Auxo.Core.Unit/
  - dotnet test test/Auxo.EFCore.Unit/
  - dotnet test test/Auxo.Location.Unit/
  - dotnet test test/Auxo.Messages.Unit/
  - dotnet test test/Auxo.Services.Unit/
  - dotnet test test/Auxo.Validation.Unit/
