language: csharp


matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003133


script:
  # Run a new console app
  - dotnet restore
  - dotnet test test/Auxo.Core.Unit/
